version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo "Installing dependencies..."
      - npm install
      - echo "Building..."
      - npm run build
artifacts:
  files:
    - '**/*'
  discard-paths: yes
